version: '3'

networks:
  main:
volumes:
  db_data:

services:

  database:
    container_name: database
    image: mysql:8.0
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: play-slick
      MYSQL_USER: play-slick
      MYSQL_PASSWORD: play-slick
    networks:
      - main

  phpmyadmin:
    container_name: phpmyadmin
    depends_on:
      - database
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8081:80'
    environment:
      PMA_HOSTS: database
      MYSQL_ROOT_PASSWORD: password
    networks:
      - main

  sbt:
    container_name: sbt
    depends_on:
      - database
    image: sbt
    build:
      context: ./docker
    ports:
      - "8080:9000"
    volumes:
      - "./:/project"
    networks:
      - main
