version: '3'

networks:
  main:
volumes:
  db_data:

services:
  db:
    image: mysql:8.0
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: scala
      MYSQL_USER: scala
      MYSQL_PASSWORD: scala
    networks:
      - main

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8081:80'
    environment:
      PMA_HOSTS: db
      MYSQL_ROOT_PASSWORD: password
    networks:
      - main

  scala:
    image: hseeberger/scala-sbt
    networks:
      - main
